apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bleme
resources:
- ../../base
# ---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: postgres-env
  literals:
  - NODE_ENV="production"
  - POSTGRES_DB="postgres"
  - POSTGRES_USER="postgres"
  - POSTGRES_PASSWORD="postgres"
  - PGDATA="/var/lib/postgresql/data/pgdata"
  