apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: https,http
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"
  name: ingress-api-bleme
spec:
  tls:
  - secretName: sectlsu
    hosts:
    - "api.bleme.fr"
  rules:
  - host: "api.bleme.fr"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-bleme
            port:
              number: 80
