apiVersion: v1
kind: PersistentVolume
metadata:
  name: front-bleme-public-pv
  labels:
    type: local
spec:
  storageClassName: manual
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/front"
  capacity:
    storage: 50Gi
