apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-payment
  labels:
    app: api-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-payment
  template:
    metadata:
      labels:
        app: api-payment
    spec:
      containers:
      - name: api-payment
        image: docker.io/widernest/api-payment:2.1.3
        envFrom:
        - configMapRef:
            name: api-payment-env
        ports:
        - containerPort: 80
        volumeMounts:
        - name: api-payment-config
          mountPath: /usr/lib/bleme/api-payment/config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: api-payment-config
        configMap:
          name: api-payment-config
