apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-env
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data-storage
      volumes:
      - name: postgres-data-storage
        persistentVolumeClaim:
          claimName: postgres-pvc