---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tfoumax
bases:
- ../../base

patches:
- target:
    group: apps
    version: v1
    kind: StatefulSet
  patch: |-
    - op: remove
      path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution



# ---
images:
- name: redis
  newName: 216775963307.dkr.ecr.eu-west-3.amazonaws.com/redis
  newTag: 3.2.3-alpine
- name: redis_exporter
  newName: 216775963307.dkr.ecr.eu-west-3.amazonaws.com/redis_exporter
  newTag: latest
