apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bleme
resources:
- ../../base
# ---
patches:
- patch: |-
    - op: add
      path: /metadata/annotations/alb.ingress.kubernetes.io~1security-groups
      value: alb.int1.athena.tf1.fr
    - op: add
      path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
      value: arn:aws:acm:eu-west-3:216775963307:certificate/15382ace-449d-431d-9ea5-27cecefae376
    - op: add
      path: /metadata/annotations/alb.ingress.kubernetes.io~1group.name
      value: tfoumax-prv-ingress-group
    - op: replace
      path: /metadata/annotations/alb.ingress.kubernetes.io~1load-balancer-attributes
      value: routing.http.drop_invalid_header_fields.enabled=true,access_logs.s3.enabled=true,access_logs.s3.bucket=etf1-audit-s3-eu-west-3-elb-logs
    - op: replace
      path: /spec/rules/0/host
      value:  tfoumax-api-geoip.int1.athena.tf1.fr
  target:
    kind: Ingress
# ---
images:
- name: api-geoip
  newName: 216775963307.dkr.ecr.eu-west-3.amazonaws.com/tfoumax/api-geoip
  newTag: 1.0.1
# ---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- literals:
  name: api-geoip-env
  - NODE_ENV="integration"
- files:
  name: api-geoip-config
  - files/config/integration.json
