---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/svc.yaml
- resources/hpa.yaml
- resources/deploy.yaml
- resources/ing.yaml
- resources/redirect.yaml
# - resources/sa.yaml
