---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - files/ssh/ssh_host_ed25519_key
  - files/ssh/ssh_host_ed25519_key.pub
  - files/ssh/ssh_host_rsa_key
  - files/ssh/ssh_host_rsa_key.pub
  - files/ssh/sshd_config
  - files/start.sh
  name: sftp-config
resources:
- resources/deploy.yaml
- resources/svc.yaml
